version: 2
jobs:
  build:
    working_directory: ~/hotsoul-blog
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo
      - run:
          name: build hugo
          command: hugo -t hotsoul-blog
      - save_cache:
          key: hotsoul-blog-public-{{ epoch }}
          paths:
            - ~/hotsoul-blog/public

  deploy:
    working_directory: ~/public-repo
    machine:
      enabled: true
      timezone: Asia/Tokyo
    steps:
      - run:
          name: clone
          command: git clone https://github.com/hotsoul/hotsoul.github.io.git
      - run:
          name: clean
          command: |
            cd hotsoul.github.io
            mv CNAME ../
            mv .git ../
            rm -rf ./*
            mv ../CNAME ./
            mv ../.git ./
            ls -la
      - restore_cache:
          keys:
            - hotsoul-blog-public
      - run:
          name: push contents
          command: |
            cd hotsoul.github.io
            mv ~/hotsoul-blog/public/* ./
            git add .
            git commit -m "[ci skip] push new contents"
            git push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
