version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo
     - run:
          name: echo-dir
          command: pwd
      - run:
          name: build hugo
          command: hugo -t hotsoul-blog
