version: 2
jobs:
  build:
    working_directory: ~/hotsoul-blog
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo
      - run:
          name: build hugo
          command: hugo -t hotsoul-blog
      - save_cache:
          key: hotsoul-blog-public-{{ epoch }}
          paths:
            - ~/hotsoul-blog/public

  deploy:
    working_directory: ~/hotsoul.github.io
    machine: true
    steps:
      - checkout
      - run:
          name: clean
          command: |
            pwd
            ls -la
            ls -lR
      - restore_cache:
          keys:
            - hotsoul-blog-public

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
